### ISSUE TITLE
 Issue with plugin panel alignment

### ISSUE THREAD

**Issue by nevertoday** [tadashi-aikawa/obsidian-another-quick-switcher#156]
I encountered an issue with the plugin where after using cmd+o, the panel does not align in the center, but instead appears on the right side. This is very strange and I have not been able to find a solution. 
![image](https://user-images.githubusercontent.com/166048/226158879-eb60ce1e-5ebe-4d63-bee6-554b39695a5e.png)

**Comment by nevertoday** [comment]
I use below  css as trick 

```css
.another-quick-switcher__floating-prompt {
  left: 50% !important;
  transform: translateX(-50%) !important;
}
```
