### ISSUE TITLE
Feature Request: Visually Emphasis Starred Items

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#32]
I am using the starred Core Plugin, and I thought it would be a nice touch to add?

Looking through the console, it seems that this will output a list of all starred items:

```js
app.internalPlugins.plugins.starred.instance.items
    .filter (item => item.type === "file");
```

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser.

Looks good 👍

**Comment by tadashi-aikawa** [comment]
Highlight with icons ☺️ 

![image](https://user-images.githubusercontent.com/9500018/162610282-a96a1a41-dd14-4375-a5eb-2f42124707cf.png)

If you use a theme that doesn't have a gutter or prefer another style, you need to customize `.another-quick-switcher__item` or `.another-quick-switcher__item::before` style.

**Comment by chrisgrieser** [comment]
> If you use a theme that doesn't have a gutter or prefer another style, you need to customize .another-quick-switcher__item or .another-quick-switcher__item::before style.

I actually do style Another Quick Switcher quite extensively in my theme 😆 
So will do! however, I always disliked the Gutter in the Quick Switchers, since looks weird when there is nothing in it. A better solution could be to either place the star *after* the text, next to the folder, or to prepend it to the text, so you do not need a gutter?

**Comment by tadashi-aikawa** [comment]
> A better solution could be to either place the star after the text, next to the folder, or to prepend it to the text

Probably, you can by customizing CSS. If you couldn't, it would be great to ask me here 👍

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Released [v4.8.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.8.0) 🚀

**Comment by chrisgrieser** [comment]
fantastic, the css class was already enough for me. 🤩 

```css
.another-quick-switcher__starred_item::before {
	display: none;
}

.another-quick-switcher__starred_item .another-quick-switcher__item__title::after {
	content: "☆";
	padding-left: 5px;
}

.another-quick-switcher__starred_item {
	font-weight: 600;
}
```

here's how it looks in my theme:
<img width="1047" alt="Screenshot 2022-04-10 19 08 52" src="https://user-images.githubusercontent.com/73286100/162631168-1ac78cd4-474d-4dae-8e83-338113a7a554.png">
