### ISSUE TITLE
FR: Numbers for quicker result selection

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#47]
some apps offer shortcuts to select specific search results, to save one from repeatedly clicking arrow-down or cmd/ctrl+j to get to a certain search result. Maybe something in that regard could also be a nice feature for AQS?
![image](https://user-images.githubusercontent.com/73286100/170961951-ae87e150-6c54-4568-af63-a5e087553dee.png)

**Comment by tadashi-aikawa** [comment]
Does it satisfy your requirements by changing from

```html
<span class="another-quick-switcher__item__hot-key-guide">[2]</span>
```

to

```html
<span class="another-quick-switcher__item__hot-key-guide">2</span>
```
 
?

**Comment by chrisgrieser** [comment]
sure, that would also work!

You can also simply add these to the `styles.css`, which would result in the same `[2]`, but woudl be more easier for theme devs to style
```css
.another-quick-switcher__item__hot-key-guide::before {
	content: "[";
}
.another-quick-switcher__item__hot-key-guide::after {
	content: "]";
}
```
