### ISSUE TITLE
Can the user choose where to place the serial number?

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-another-quick-switcher#74]
In the old version, the serial number was followed by the title of the note, which was convenient for users to know at a glance which key to press to open the note, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/56342788/177283115-d65a46ef-3d83-45c0-b332-50621922fd25.png)

However, in the new version, the serial number has been placed on the far right. If the title is short, it is very difficult to judge which serial number a note corresponds to.

![image](https://user-images.githubusercontent.com/56342788/177283591-6272f88c-dac2-451e-be11-910a54c29c90.png)

Can the user choose where to place the serial number? Best regards.

**Comment by tadashi-aikawa** [comment]
Hi, @tyf2018 :)

You can set style by following CSS.

```css
.another-quick-switcher__item__title {
  flex: initial !important;
  padding: 0 !important;
}
.another-quick-switcher__item__hot-key-guide {
  flex: 1;
}
.another-quick-switcher__item__directory {
  margin-left: auto;
  white-space: pre;
}
```

![image](https://user-images.githubusercontent.com/9500018/177327219-d5e354d2-167f-443a-a157-3dfc9d243e43.png)
